### ISSUE TITLE
qemu@7.2.0-rc4: decompress error

### ISSUE THREAD

**Issue by sogwms** [ScoopInstaller/Main#4243] opened 2022-12-18 02:54 UTC
When I try to install qemu 7.2.0-rc4, an error occurs “Failed to extract files qemu\7.2.0-rc4\dl.7z.”. Unfortunately, it seems that the current qemu only has this version and I am unable to install another version (such as 7.1.0).

**Comment by rashil2000** [comment] 2022-12-18 07:33
Duplicate of #4164

**Closed by rashil2000** 2022-12-18 07:33 UTC
