### ISSUE TITLE
[Bug]: Miktex 404 error on update

### ISSUE THREAD

**Issue by jawadcode** [ScoopInstaller/Main#4680] opened 2023-04-17 22:00 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

miktex

### Expected/Current Behaviour

Expected Behaviour: Miktex should update to the latest version when `scoop update *` is run

### Steps to Reproduce

```console
> scoop update *
miktex: 22.10 -> 23.4
rust-analyzer: 2023-04-10 -> 2023-04-17
Updating 2 outdated apps:
Updating 'miktex' (22.10 -> 23.4)
Downloading new version
OperationStopped: C:\Users\jawad\scoop\apps\scoop\current\lib\install.ps1:111
Line |
 111 |          throw $e
     |          ~~~~~~~~
     | The remote server returned an error: (404) Not Found.

> scoop uninstall miktex
Uninstalling 'miktex' (22.10).
Removing shim 'miktex.shim'.
Removing shim 'miktex.exe'.
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\MiKTeX Console.lnk
Unlinking ~\scoop\apps\miktex\current
Removing ~\scoop\apps\miktex\current\texmfs\install\miktex\bin\x64 from your path.
'miktex' was uninstalled.

> scoop update *
rust-analyzer: 2023-04-10 -> 2023-04-17
Updating one outdated app:
Updating 'rust-analyzer' (2023-04-10 -> 2023-04-17)
Downloading new version
rust-analyzer-x86_64-pc-windows-msvc.gz (9.5 MB) [================================================================================================================================================] 100%
Checking hash of rust-analyzer-x86_64-pc-windows-msvc.gz ... ok.
Uninstalling 'rust-analyzer' (2023-04-10)
Removing shim 'rust-analyzer.shim'.
Removing shim 'rust-analyzer.exe'.
Unlinking ~\scoop\apps\rust-analyzer\current
Installing 'rust-analyzer' (2023-04-17) [64bit] from main bucket
Loading rust-analyzer-x86_64-pc-windows-msvc.gz from cache
Extracting rust-analyzer-x86_64-pc-windows-msvc.gz ... done.
Running pre_install script...
Linking ~\scoop\apps\rust-analyzer\current => ~\scoop\apps\rust-analyzer\2023-04-17
Creating shim for 'rust-analyzer'.
'rust-analyzer' (2023-04-17) was installed successfully!

> scoop install miktex
Installing 'miktex' (23.4) [64bit] from main bucket
The remote server returned an error: (404) Not Found.
URL https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/basic-miktex-23.4-x64.exe is not valid
```

### Possible Solution

The version of miktex should be rolled back to 22.10 as that is the latest available under the mirror: https://mirror.ox.ac.uk/sites/ctan.org/systems/win32/miktex/setup/windows-x64/

### Scoop and Buckets Version

```console
> scoop --version

Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
253c8b381 (HEAD -> master, origin/master, origin/HEAD) fastcopy: Fix persistence (#11075)

'main' bucket:
872ba77e0 (HEAD -> master, origin/master, origin/HEAD) zeebe: Update to version 8.2.2

'nonportable' bucket:
fb9f8cd (HEAD -> master, origin/master, origin/HEAD) unity-hub-np: Update to version 3.4.2
```

### Scoop Config

```console
> scoop config

last_update         scoop_repo                              scoop_branch
-----------         ----------                              ------------
17/04/2023 22:39:42 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by rashil2000** [comment] 2023-04-18 05:16
Upstream issue: https://github.com/MiKTeX/miktex/issues/1318

**Comment by JP-Ellis** [comment] 2023-04-18 07:44
and this ticket is a duplicate of #4679

**Comment by magneticflux-** [comment] 2023-04-19 01:14
I was able to download it eventually, but the download still fails sometimes depending on the mirror that is randomly selected. Using Curl instead of Aria2 might cause it to try more mirrors before failing. Here are some of the working mirrors I found: https://github.com/MiKTeX/miktex/issues/1318#issuecomment-1513994306

**Comment by rashil2000** [comment] 2023-04-19 08:09
Updated the manifests with the mit.edu mirrors: https://github.com/ScoopInstaller/Main/commit/cecb4a688b64a880a0f8330f6fbbea55aa5e19db

**Closed by rashil2000** 2023-04-19 08:09 UTC
Labels: upstream
