### ISSUE TITLE
scoop status not showing firefox-developer as out of date

### ISSUE THREAD

**Issue by LoZeno** [ScoopInstaller/Main#456] opened 2019-09-30 08:41 UTC
I have firefox-developer installed, currently at version 70.0b9  
After doing a `scoop update` I see that there's a new version available (70.0b10)
Typing `scoop status`, though, says that everything is up to date; typing `scoop update firefox-developer` or `scoop update *` returns the same message (everything is up to date);

The workaround is to uninstall and reinstall, which is not very useful because it means that I have to manually check the versions installed and the versions available for each app, thus defeating the purpose of `scoop status`

**Comment by Ash258** [comment] 2019-09-30 08:44
Duplicate of lukesampson/scoop#2720

**Closed by Ash258** 2019-09-30 08:44 UTC
