### ISSUE TITLE
`az` command from `azure-cli` package fails to launch

### ISSUE THREAD

**Issue by adamency** [ScoopInstaller/Main#3197] opened 2022-01-16 23:52 UTC
## Bug Report

**Package Name:** azure-cli

### Current Behaviour

After installation, running `az` with any option, let's say `az --version` results in an error message: 

```
The system cannot find the path specified.
```

### Expected Behaviour

Running `az --version` results in a correct output showing the version of the program

### Additional context/output

Tested on Powershell 7.2.1 and Windows Powershell 5.1.22000.282 and Cmd.exe, all three in Windows Terminal and in Normal Windows Command Prompt, both as normal and administrative. Same behavior on all.

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

#### Scoop Configuration

```json
{
  "lastupdate": "2022-01-17T00:25:41.3250330+01:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master"
}
```

**Comment by rashil2000** [comment] 2022-01-17 04:38
Cannot reproduce.

![image](https://user-images.githubusercontent.com/46838874/149708743-d55fb243-b0fb-4061-a413-88528ffb2cb2.png)


I think your antivirus might be interfering here. 
- Check if it hasn't deleted any files. 
- Add an exception for the ~\scoop folder. 
- Reinstall azure-cli.

**Comment by adamency** [comment] 2022-01-17 10:07
It doesn't have anything to do with an antivirus...

This is most likely because my username has a diacritic in it (namely `é`) and scoop incorrectly marks the character as a `?` instead in all filepaths. And I can't do anything about it: it's on my work machine and was set by my company.

However, even after correcting all paths, I still get the same error message.

By the way, there are two files in `~/scoop/shims/`: `az` and `az.cmd`. Counterintuitively, this is the second one that is actually called when typing `az` in the path. You can verify this by calling the files by their full path. After deleting the file `az.cmd`, then running `az` will effectively try to run the actual file `az` but windows will ask how we want to open it, i.e. doesn't recognize the file as an executable.

Lastly, if I go to `~/scoops/apps/azure-cli/current/wbin/` and run the `az` file there, it runs successfully and I get the correct output as you have shown.

To me there's an issue with the redirection of the file in `shims` to the actual executable.

**Comment by rashil2000** [comment] 2022-01-17 13:29
The 2 shims are created for different types of shells - `az` for Unix shells (MSYS2, Cygwin), and `az.cmd` for Cmd, Powershell and all others. So they are necessary. 

The issue about diacritics in path is tracked here - https://github.com/ScoopInstaller/Scoop/issues/2230 - so I'll close this one.

**Closed by rashil2000** 2022-01-17 13:29 UTC
Labels: bug

**Comment by adamency** [comment] 2022-01-17 15:37
Thanks for the explanation.
