### ISSUE TITLE
[Windows] Neofetch package is calling "bash.exe" from a ghost path 

### ISSUE THREAD

**Issue by akiyuee** [ScoopInstaller/Main#3587] opened 2022-05-18 11:43 UTC
## Bug Report

**Package Name:** `neofetch`

### Current Behaviour
Currently, after you have installed git and neofetch, the `neofetch.cmd` file in `\scoop\shims` will call a non-existent `bash.exe` file.  
In return, it will throw out "The system cannot find the path specified" error  
![image](https://user-images.githubusercontent.com/67498765/169029940-fa319a47-1bb5-4356-a9b3-a06930df797c.png)  

Reference: [#3562]

### Expected Behaviour
It should run

### Possible Solution  
The path should be like this:  
```bat
@"C:\Users\%username%\scoop\apps\git\current\bin\bash.exe" "C:\Users\%username%\scoop\apps\neofetch\current\neofetch"  %*
```

**Comment by rashil2000** [comment] 2022-05-18 11:49
Duplicate of https://github.com/ScoopInstaller/Main/issues/3562

**Closed by rashil2000** 2022-05-18 11:49 UTC
Labels: bug
