### ISSUE TITLE
ffmpeg@4.3.1-26: Download failed

### ISSUE THREAD

**Issue by rofrol** [ScoopInstaller/Main#1699] opened 2020-12-22 20:06 UTC
Looks like the release was removed.

```
Installing 'ffmpeg' (4.3.1-26) [64bit]
Serwer zdalny zwrócił błąd: (404) Nie znaleziono.
URL https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2020-12-08-13-03/ffmpeg-n4.3.1-26-gca55240b8c-win64-gpl-4.3.zip is not valid
```

**Comment by CrendKing** [comment] 2020-12-23 20:28
Duplicate of https://github.com/ScoopInstaller/Main/issues/1659

**Closed** 2021-03-08 13:48 UTC
Labels: help-wanted, package-fix-needed, verified, verify
