### ISSUE TITLE
gcc@9.3.0-2: Download via aria2 failed

### ISSUE THREAD

**Issue by M-FeD** [ScoopInstaller/Main#1982] opened 2021-03-25 14:15 UTC
PS C:\Users\mfed> scoop install gcc
Installing 'gcc' (9.3.0-2) [64bit] [main]
WARN  By installing you accept following licenses:
  GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later.html)
  ZPL-2.1 (https://spdx.org/licenses/ZPL-2.1.html)
Loading mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gcc-9.3.0-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gcc-fortran-9.3.0-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gcc-libgfortran-9.3.0-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gcc-libs-9.3.0-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gmp-6.2.0-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-headers-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-isl-0.22.1-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-libwinpthread-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-make-4.3-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-mpc-1.1.0-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-mpfr-4.0.2-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-winpthreads-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz from cache.
Starting download with aria2 ...
Download: 03/25 14:10:37 [ERROR] CUID#8 - Download aborted. URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expaDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-Download: 03/25 14:10:37 [ERROR] CUID#10 - Download aborted. URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libicoDownload: 03/25 14:10:37 [ERROR] CUID#11 - Download aborted. URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-pkgDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-pkg-coDownload: 03/25 14:10:37 [ERROR] CUID#9 - Download aborted. URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gettDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gettexDownload: 03/25 14:10:37 [ERROR] CUID#12 - Download aborted. URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-zliDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-zlib-1Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: b64ecd|ERR |       0B/s|C:/Users/mfed/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz
Download: 26377f|ERR |       0B/s|C:/Users/mfed/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz
Download: 60bc80|ERR |       0B/s|C:/Users/mfed/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz
Download: 4c4f6b|ERR |       0B/s|C:/Users/mfed/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz
Download: 801b9c|ERR |       0B/s|C:/Users/mfed/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\mfed\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\mfed\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\mfed\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\mfed\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\mfed\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz

ERROR & 'C:\Users\mfed\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\mfed\scoop\cache\gcc.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=12404 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=gcc%409.3.0-2%3a+Download+via+aria2+failed&body=Download+failed!+(Error+3)+Resource+was+not+found

**Comment by chawyehsu** [comment] 2021-03-31 15:50
Duplicate of #1752

**Closed by chawyehsu** 2021-03-31 15:50 UTC
Labels: help-wanted, package-fix-needed, verified
