### ISSUE TITLE
aws-sam-cli@1.36.0: decompress error

### ISSUE THREAD

**Issue by pupeno** [ScoopInstaller/Main#3059] opened 2021-12-07 21:49 UTC
For the past hour and after trying about 20 times, I'm still getting this error when trying to install aws-sam-cli:

```
> scoop install aws-sam-cli
WARN  Purging previous failed installation of aws-sam-cli.
Uninstalling 'aws-sam-cli' ().
'aws-sam-cli' was uninstalled.
Installing 'aws-sam-cli' (1.36.0) [64bit]
Loading AWS_SAM_CLI_64_PY3.msi from cache
Checking hash of AWS_SAM_CLI_64_PY3.msi ... ok.
Extracting AWS_SAM_CLI_64_PY3.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\pupeno\scoop\apps\aws-sam-cli\1.36.0\AWS_SAM_CLI_64_PY3.msi.
Log file:
  ~\scoop\apps\aws-sam-cli\1.36.0\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=aws-sam-cli%401.36.0%3a+decompress+error
```

`msi.log` contains:

```
=== Logging started: 07/12/2021  21:38:29 ===
Error 1304. Error writing to file: C:\Users\pupeno\scoop\apps\aws-sam-cli\1.36.0\_tmp\SourceDir\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\init\templates\cookiecutter-aws-sam-hello-java-gradle\{{cookiecutter.project_name}}\HelloWorldFunction\src\main\java\helloworld\GatewayResponse.java. Verify that you have access to that directory.
=== Logging stopped: 07/12/2021  21:38:48 ===
```

**Comment by rashil2000** [comment] 2021-12-08 05:43
Did you try searching for already existing issues?

**Comment by pupeno** [comment] 2021-12-08 09:21
Yes, did I miss something?

**Comment by rashil2000** [comment] 2021-12-08 09:26
Duplicate of #2775

**Closed** 2021-12-08 09:26 UTC
