### ISSUE TITLE
cacert update failing

### ISSUE THREAD

**Issue by midaspt** [ScoopInstaller/Main#3732] opened 2022-07-01 17:51 UTC
## Bug Report

**cacert**

### Current Behaviour

Since last February, I have been unable to update **cacert** -- it always throws an error:

> `+ CategoryInfo          : OperationStopped: (:) [], WebException`
> `+ FullyQualifiedErrorId : The request was aborted: Could not create SSL/TLS secure channel.`

When this error happens, **scoop** stops updating so I had to place this package on hold.

Today I decided to uninstall it and try to reinstall it, only to get another error:

> `Installing 'cacert' (2022-04-26) [64bit]`
> `The request was aborted: Could not create SSL/TLS secure channel.`
> `URL https://curl.haxx.se/ca/cacert-2022-04-26.pem#/cacert.pem is not valid`

### Expected Behaviour

Updating should proceed as normal, since **scoop** alerts me to the existence of an update.

> `PS C:\Users\User> scoop update *`
> `cacert: 2022-02-01 -> 2022-04-26`

**Windows version:** **7** <= Probably the cause, since this doesn't happen in **10**

**OS architecture:** 64bit

**PowerShell version:** 
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1018
```

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-07-01T18:16:16.3983815+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

**Comment by rashil2000** [comment] 2022-07-01 20:13
Duplicate of https://github.com/ScoopInstaller/Main/issues/3593

**Closed by rashil2000** 2022-07-01 20:13 UTC
Labels: bug
