### ISSUE TITLE
tesseract@5.3.0.20221214: decompress error

### ISSUE THREAD

**Issue by Joker1718** [ScoopInstaller/Main#4240] opened 2022-12-17 13:27 UTC
ERROR Exit code was 2!
Failed to extract files from C:\Users\Admin\scoop\apps\tesseract\5.3.0.20221214\dl.7z.
Log file:
  ~\scoop\apps\tesseract\5.3.0.20221214\7zip.log

**Comment by rashil2000** [comment] 2022-12-18 07:42
Duplicate of #4230

**Closed by rashil2000** 2022-12-18 07:42 UTC
