### ISSUE TITLE
less@551: download via aria2 failed

### ISSUE THREAD

**Issue by nklowns** [ScoopInstaller/Main#457] opened 2019-09-30 18:55 UTC
```cmd
Installing 'less' (551) [64bit]
Starting download with aria2 ...
Download: 09/30 15:46:07 [ERROR] CUID#8 - Download aborted. URI=https://www.guysalias.tk/misc/less/less-551-win32-static-x86.7z
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://www.guysalias.tk/misc/less/less-551-win32-static-x86.7z
Download:   -> [SocketCore.cc:1015] errorCode=1 SSL/TLS handshake failure: Error: A cadeia de certifica├º├úo foi emitida por uma autoridade que n├úo ├® de confian├ºa.
Download: (80090325)
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 66053f|ERR |       0B/s|C:/Oongbsd/Scoop/cache/less#551#https_www.guysalias.tk_misc_less_less-551-win32-static-x86.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://www.guysalias.tk/misc/less/less-551-win32-static-x86.7z
    referer=https://www.guysalias.tk/misc/less/
    dir=C:\Oongbsd\Scoop\cache
    out=less#551#https_www.guysalias.tk_misc_less_less-551-win32-static-x86.7z

ERROR & 'C:\Oongbsd\Scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Oongbsd\Scoop\cache\less.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=7172 --continue
```

**Comment by jkrehm** [comment] 2019-10-07 13:36
Duplicate of #150 (apparently the file is available currently, but behind a self-signed certificate).

**Comment by wuya666** [comment] 2019-10-11 15:16
> Duplicate of #150 (apparently the file is available currently, but behind a self-signed certificate).

Any idea how to get scoop to install it? Some way to bypass the SSL check?

**Comment by r15ch13** [comment] 2019-10-11 17:17
Busybox provides less. Would this be a suitable replacement? It may not have all features though.

**Closed** 2019-11-13 21:36 UTC
