### ISSUE TITLE
ollama@0.1.44: decompress error

### ISSUE THREAD

**Issue by kimagin** [ScoopInstaller/Main#5917] opened 2024-06-16 12:17 UTC
I keep receiving this issue : 

❯ scoop install ollama
Installing 'ollama' (0.1.44) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\info\scoop\apps\ollama\0.1.44\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.1.44\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.1.44%3a+decompress+error

I am using Powershell 7.4.2 in windows 11 and I was able to run scoop install ollama in a previous version but not on 0.1.44

**Comment by HUMORCE** [comment] 2024-08-01 20:23
Duplicate of #6065

**Closed by HUMORCE** 2024-08-01 20:23 UTC
