### ISSUE TITLE
ollama@0.1.44: decompress error

### ISSUE THREAD

**Issue by sharno** [ScoopInstaller/Main#5912] opened 2024-06-15 03:55 UTC
```
Installing 'ollama' (0.1.44) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\sharno\scoop\apps\ollama\0.1.44\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.1.44\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.1.44%3a+decompress+error
```

file innounp.log:
```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.
```

**Comment by HUMORCE** [comment] 2024-08-01 20:23
Duplicate of #6065

**Closed by HUMORCE** 2024-08-01 20:23 UTC
