### ISSUE TITLE
gcc@9.3.0-2: download via aria2 failed

### ISSUE THREAD

**Issue by cfl1538** [ScoopInstaller/Main#1764] opened 2021-01-19 10:06 UTC
Hi, i wonder why i can't install gcc via scoop. Thanks.

PS C:\Users\Administrator> scoop install gcc
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'gcc' (9.3.0-2) [64bit]
Loading mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gcc-9.3.0-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gcc-fortran-9.3.0-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gcc-libgfortran-9.3.0-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gcc-libs-9.3.0-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-gmp-6.2.0-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-headers-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-isl-0.22.1-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-libwinpthread-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-make-4.3-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-mpc-1.1.0-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-mpfr-4.0.2-2-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-winpthreads-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz from cache.
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: c3f6bf|ERR |       0B/s|D:/Applications/Scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz
Download: ec0561|ERR |       0B/s|D:/Applications/Scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz
Download: 44708e|ERR |       0B/s|D:/Applications/Scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz
Download: a6f990|ERR |       0B/s|D:/Applications/Scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz
Download: 5b1cfe|ERR |       0B/s|D:/Applications/Scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=D:\Applications\Scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=D:\Applications\Scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=D:\Applications\Scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=D:\Applications\Scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=D:\Applications\Scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz

ERROR & 'D:\Applications\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Applications\Scoop\cache\gcc.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=16 --max-connection-per-server=16 --min-split-size=1M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=10416 --continue --summary-interval 0
![image](https://user-images.githubusercontent.com/50565774/105019337-f359e280-5a80-11eb-9094-ea9d8d0582fc.png)

**Comment by chawyehsu** [comment] 2021-03-10 01:49
Duplicate of #1752

**Closed by chawyehsu** 2021-03-10 01:49 UTC
Labels: help-wanted, package-fix-needed, verified
