### ISSUE TITLE
ollama@0.3.0: decompress error

### ISSUE THREAD

**Issue by vervoortkobe** [ScoopInstaller/Main#6059] opened 2024-07-29 21:28 UTC
PS C:\Users\Gebruiker> scoop install main/ollama
Installing 'ollama' (0.3.0) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\Gebruiker\scoop\apps\ollama\0.3.0\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.3.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.3.0%3a+decompress+error

**Comment by HUMORCE** [comment] 2024-08-01 20:22
Duplicate of #6065

**Closed by HUMORCE** 2024-08-01 20:22 UTC
