### ISSUE TITLE
azure-cli@2.52.0: decompress error

### ISSUE THREAD

**Issue by BProulx02** [ScoopInstaller/Main#5110] opened 2023-09-15 18:31 UTC
I'm unable to update my version of azure-cli from 2.48.1 to 2.52.0. I'm getting the following error message :

```
Extracting azure-cli-2.52.0.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Development-Tools\CLI-Utilities\Scoop\apps\azure-cli\2.52.0\azure-cli-2.52.0.msi.
Log file:
  C:\Development-Tools\CLI-Utilities\Scoop\apps\azure-cli\2.52.0\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=azure-cli%402.52.0%3a+decompress+error
```

(Attached is the [msi.log](https://github.com/ScoopInstaller/Main/files/12622667/msi.log) file mentionned above)

**Comment by SeWieland** [comment] 2023-09-17 16:14
Duplicate of #5107 - and I can confirm the error as well

**Closed** 2023-09-17 16:16 UTC
