### ISSUE TITLE
gcc@9.3.0-2: download via aria2 failed

### ISSUE THREAD

**Issue by Eyepan** [ScoopInstaller/Main#1868] opened 2021-02-25 10:32 UTC
`ERROR Download failed! (Error 3) Resource was not found                                                              ERROR https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz                                  referer=https://repo.msys2.org/mingw/x86_64/                                                                         dir=C:\Users\iamte\scoop\cache                                                                                       out=gcc#9.3.0-2#https_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz                  https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz                                   referer=https://repo.msys2.org/mingw/x86_64/                                                                         dir=C:\Users\iamte\scoop\cache                                                                                       out=gcc#9.3.0-2#https_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz             https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz                                      referer=https://repo.msys2.org/mingw/x86_64/                                                                         dir=C:\Users\iamte\scoop\cache                                                                                       out=gcc#9.3.0-2#https_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz                https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz                                  referer=https://repo.msys2.org/mingw/x86_64/                                                                         dir=C:\Users\iamte\scoop\cache                                                                                       out=gcc#9.3.0-2#https_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz            https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz                                        referer=https://repo.msys2.org/mingw/x86_64/                                                                         dir=C:\Users\iamte\scoop\cache                                                                                       out=gcc#9.3.0-2#https_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz                                                                                                                                       ERROR & 'C:\ProgramData\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\iamte\scoop\cache\gcc.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=29640 --continue --summary-interval 0`

**Comment by chawyehsu** [comment] 2021-03-10 01:49
Duplicate of #1752

**Closed by chawyehsu** 2021-03-10 01:49 UTC
Labels: help-wanted, package-fix-needed, verified
