### ISSUE TITLE
ollama@0.1.44: decompress error

### ISSUE THREAD

**Issue by dna1000** [ScoopInstaller/Main#5909] opened 2024-06-14 08:58 UTC
It seems the latest version of llama is packed with inno version 6.3.0 but the innounp application installed with scoop (and indeed is what appears to be the latest version available 0.50, which looks to only be able to unpack up to version 6.1.2).

I've searched for a later version of innounp that can unpack 6.3.0 but there doesn't seem to be anything available.

Scoop error message:
"Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\user\xxxxx\scoop\apps\ollama\0.1.44\OllamaSetup.exe."

from log file
"Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program."

**Comment by HUMORCE** [comment] 2024-08-01 20:23
Duplicate of #6065

**Closed by HUMORCE** 2024-08-01 20:23 UTC
