### ISSUE TITLE
qemu@7.2.0-rc3: decompress error

### ISSUE THREAD

**Issue by thgwalter** [ScoopInstaller/Main#4185] opened 2022-12-01 22:51 UTC
Same as with rc2 ; there is a decompress error.

**Comment by SamJakob** [comment] 2022-12-02 00:27
Whilst I get the decompress error it does seem to successfully install so I'm not sure exactly what's failing to decompress.

**Comment by SamJakob** [comment] 2022-12-02 00:28
Ah, indeed I think this is the same issue as #4164

**Comment by rashil2000** [comment] 2022-12-02 02:40
Duplicate of #4164

**Closed by rashil2000** 2022-12-02 02:40 UTC
