### ISSUE TITLE
nmap@7.94: Shim creation fail

### ISSUE THREAD

**Issue by jshifrin25** [ScoopInstaller/Main#4827] opened 2023-05-22 15:06 UTC
Installing 'nmap' (7.94) [64bit] [main]
WARN  By installing you accept following license: GPL-2.0-only (https://github.com/nmap/nmap/blob/master/COPYING)
Loading nmap-7.94-setup.exe from cache
Checking hash of nmap-7.94-setup.exe ... ok.
Extracting dl.7z ... done.
Running pre-install script...
Linking ~\scoop\apps\nmap\current => ~\scoop\apps\nmap\7.94
Creating shim for 'nmap'.
Creating shim for 'ncat'.
Creating shim for 'ndiff'.
ERROR Cannot shim 'ndiff.exe': File does not exist

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=nmap%407.94%3a+Shim+creation+fail&body=Cannot+shim+%27ndiff.exe%27%3a+File+does+not+exist
ERROR This application failed to install: main/nmap

**Comment by YDX-2147483647** [comment] 2023-05-23 02:22
I've also met this problem…

Note that this is duplicate of #4826 , and possibly fixed by #4826 .

**Closed** 2023-05-23 17:16 UTC

**Comment by bt4ibwem8** [comment] 2025-08-13 07:00
why is nmap marked by Scoop as "**deprecated**"?
