### ISSUE TITLE
ollama@0.1.44: decompress error

### ISSUE THREAD

**Issue by otavio-silva** [ScoopInstaller/Main#5910] opened 2024-06-14 17:06 UTC
```
Updating 'ollama' (0.1.43 -> 0.1.44)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: abe02b|OK  |    46MiB/s|C:/Users/otavi/scoop/cache/ollama#0.1.44#https_github.com_ollama_ollama_releases_download_v0.1.44_OllamaSetup.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of OllamaSetup.exe ... ok.
Uninstalling 'ollama' (0.1.43)
Removing shim 'ollama.shim'.
Removing shim 'ollama.exe'.
Unlinking ~\scoop\apps\ollama\current
Installing 'ollama' (0.1.44) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\otavi\scoop\apps\ollama\0.1.44\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.1.44\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.1.44%3a+decompress+error

```

**Comment by HUMORCE** [comment] 2024-08-01 20:23
Duplicate of #6065

**Closed by HUMORCE** 2024-08-01 20:23 UTC
