### ISSUE TITLE
Support for Linux and MacOS

### ISSUE THREAD

**Issue by outforpublic** [ScoopInstaller/Main#651] opened 2019-12-16 16:24 UTC
So, Powershell 6 is released with support for Linux and MacOS. This extends our support if you want to Many different varieties of operating systems as seen <a href="https://github.com/PowerShell/PowerShell#get-powershell">Here</a>.

The way I see we can add support would be to add more JSON primitives such as
<ul>
<li>OS:</li>
    <ul><li>Windows</li>
        <ul>
        <li>URL</li>
        <li>Hash</li>
        </ul>
    <li>MacOS</li>
        <ul>
        <li>URL</li>
        <li>Hash</li>
        </ul>
     <li>Linux</li>
        <ul>
        <li>Deb</li>
        <ul>
             <li>URL</li>
             <li>Hash</li>
        </ul>
        <li>RPM</li>
        <ul>
            <li>URL</li>
            <li>Hash</li>
        </ul>
    </ul>
</ul>
</ul>

However, this will need to create script that will detect the operating system, Edit the install and Shims script.

<b>Yes, this may seem like almost a total rewrite of Scoop but I think with this team, We might be able to get it done. Like if you think so too!</b>

**Comment by Ash258** [comment] 2019-12-16 16:25
Duplicate of lukesampson/scoop#2137

**Closed by Ash258** 2019-12-16 16:25 UTC
