### ISSUE TITLE
less@551: download via aria2 failed

### ISSUE THREAD

**Issue by hatzkel** [ScoopInstaller/Main#561] opened 2019-11-12 00:26 UTC
I encountered the following after scoop update *

```
Updating 'less' (550 -> 551)
Downloading new version
Starting download with aria2 ...
Download: 11/11 19:23:12 [ERROR] CUID#8 - Download aborted. URI=https://www.guysalias.tk/misc/less/less-551-win32-static-x86.7z
Download: Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://www.guysalias.tk/misc/less/less-551-win32-static-x86.7z
Download:   -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: The certificate chain was issued by an authority that is not trusted.
Download: (80090325)
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 7dea59|ERR |       0B/s|C:/Users/hat/scoop/cache/less#551#https_www.guysalias.tk_misc_less_less-551-win32-static-x86.7z
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://www.guysalias.tk/misc/less/less-551-win32-static-x86.7z
    referer=https://www.guysalias.tk/misc/less/
    dir=C:\Users\hat\scoop\cache
    out=less#551#https_www.guysalias.tk_misc_less_less-551-win32-static-x86.7z

ERROR & 'C:\Users\hat\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\hat\scoop\cache\less.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/6.1 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6508 --continue

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Schttps://github.com/ScoopInstaller/Main/issues/new?title=less%40551%3a+download+via+aria2+faileds\hat>
```

Any suggestions? Not quite sure whats going on other than the CA failure. Is that what is causing the failure? I don't think so but anyone have an idea whats going on?

**Comment by linsui** [comment] 2019-11-13 13:24
duplicate of https://github.com/ScoopInstaller/Main/issues/557 https://github.com/ScoopInstaller/Main/issues/457 https://github.com/ScoopInstaller/Main/issues/409 https://github.com/ScoopInstaller/Main/issues/150

**Closed** 2019-11-13 21:36 UTC
