### ISSUE TITLE
neovim@0.3.7: hash check failed

### ISSUE THREAD

**Issue by exnisse** [ScoopInstaller/Main#98] opened 2019-05-29 18:12 UTC
Checking hash of nvim-win64.zip ... ERROR Hash check failed!
App:         main/neovim
URL:         https://github.com/neovim/neovim/releases/download/v0.3.7/nvim-win64.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    a382844cca60e110d6c7205a869d156000b093d6205df81bc1283ff19328010d
Actual:      e049e28cb9d4c0c89de33f3a1266197e6b8c3bcb28677617f7117661de702235

**Comment by Ash258** [comment] 2019-05-29 18:13
Duplicate of #97 

Closed in 7a54599ada6a6f7e3612573188c4e3e763a3b361

**Closed** 2019-05-29 18:14 UTC
