### ISSUE TITLE
ollama@0.1.44: decompress error

### ISSUE THREAD

**Issue by Kamek437** [ScoopInstaller/Main#5911] opened 2024-06-15 00:44 UTC
scoop update ollama fails :

```ERROR 'ollama' isn't installed correctly.
ollama: 0.1.43 -> 0.1.44
Updating one outdated app:
Updating 'ollama' (0.1.43 -> 0.1.44)
Downloading new version
Loading OllamaSetup.exe from cache.
Checking hash of OllamaSetup.exe ... ok.
Uninstalling 'ollama' (0.1.43)
Installing 'ollama' (0.1.44) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\kamek\scoop\apps\ollama\0.1.44\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.1.44\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.1.44%3a+decompress+error```

**Comment by HUMORCE** [comment] 2024-08-01 20:23
Duplicate of #6065

**Closed by HUMORCE** 2024-08-01 20:23 UTC
