### ISSUE TITLE
ollama@0.1.44: decompress error

### ISSUE THREAD

**Issue by mishrababhishek** [ScoopInstaller/Main#5924] opened 2024-06-18 15:42 UTC
Getting error while installing ollama 
Error code 11
Windows 10
Terminal Powershell Normal and Administrative 
![Capture](https://github.com/ScoopInstaller/Main/assets/99353986/f90a0a55-036c-4d56-8882-b93ff5945025)

**Comment by HUMORCE** [comment] 2024-08-01 20:22
Duplicate of #6065

**Closed by HUMORCE** 2024-08-01 20:22 UTC
