### ISSUE TITLE
git-filter-repo@2.34.0: decompress error

### ISSUE THREAD

**Issue by peterleif** [ScoopInstaller/Main#3042] opened 2021-12-04 08:05 UTC
Console result
```
Installing 'git-filter-repo' (2.34.0) [64bit]
Loading v2.34.0.zip from cache
Checking hash of v2.34.0.zip ... ok.
Extracting v2.34.0.zip ... ERROR Exit code was 2!
Failed to extract files from C:\Users\peter\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip.
Log file:
  ~\scoop\apps\git-filter-repo\2.34.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=git-filter-repo%402.34.0%3a+decompress+error
```

Log file
```

7-Zip 21.06 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-11-24

Scanning the drive for archives:
1 file, 190207 bytes (186 KiB)

Extracting archive: C:\Users\peter\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip
--
Path = C:\Users\peter\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip
Type = zip
Physical Size = 190207
Comment = 235fed326910a90b3322bc535d643a9003f8d7e1


Sub items Errors: 2

Archives with Errors: 1

Sub items Errors: 2
```

There is no problem extracting cached zip archive file using windows system decompressor.

A similar issue is here https://github.com/ScoopInstaller/Main/issues/2290

**Comment by peterleif** [comment] 2021-12-04 08:17
Files that are failing to decompress are

- git_filter_repo.py
- filter-branch-ish

These files are originally submodule link, but they are substituted with text files in the zip archive.

Error may be related to some bugs in Github or 7-zip.

**Comment by phanirithvij** [comment] 2021-12-17 07:23
@peterleif can you still reproduce this now, after https://github.com/ScoopInstaller/Scoop/issues/4569#issuecomment-990006607 landed?

**Comment by peterleif** [comment] 2021-12-17 07:50
I changed SCOOP_BRANCH to develop and now I can see the error message from 7-zip.
```
7-Zip 21.06 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-11-24

Scanning the drive for archives:
1 file, 190207 bytes (186 KiB)

Extracting archive: C:\Users\peter\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip
--
Path = C:\Users\peter\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip
Type = zip
Physical Size = 190207
Comment = 235fed326910a90b3322bc535d643a9003f8d7e1


Sub items Errors: 2

Archives with Errors: 1

Sub items Errors: 2

ERROR: Cannot create symbolic link : クライアントは要求された特権を保有していません。 : C:\Users\peter\scoop\apps\git-filter-repo\2.34.0\git-filter-repo-2.34.0\contrib\filter-repo-demos\filter-branch-ish
ERROR: Cannot create symbolic link : クライアントは要求された特権を保有していません。 : C:\Users\peter\scoop\apps\git-filter-repo\2.34.0\git-filter-repo-2.34.0\git_filter_repo.py
```

The error message is Japanese (I'm using Japanese environment), which says "The client does not have the requested permission."
It seems that 7-zip tries to decompress symbolic link as symbolic link even on Windows (system decompressor decompresses it as a text file).

**Comment by rdbisme** [comment] 2022-01-11 18:59
Hello I just tested but 8b8da66 does not fix the problem apparently...

**Comment by rashil2000** [comment] 2022-01-11 19:01
What is the error?

**Comment by rdbisme** [comment] 2022-01-11 19:06
```
$ scoop update git-filter-repo
git-filter-repo: 2.33.0 -> 2.34.0
Updating 1 outdated app:
Updating 'git-filter-repo' (2.33.0 -> 2.34.0) [64bit]
Downloading new version
Loading v2.34.0.zip from cache
Checking hash of v2.34.0.zip ... ok.
Uninstalling 'git-filter-repo' (2.33.0)
WARN  Shim for 'git-filter-repo' is missing. Skipping.
Installing 'git-filter-repo' (2.34.0) [64bit] [main]
WARN  By installing you accept following license: MIT (https://spdx.org/licenses/MIT.html)
Loading v2.34.0.zip from cache
Extracting v2.34.0.zip ... ERROR Exit code was 2!
ERROR Failed to extract files from C:\Users\rdibattista\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip.
Log file:
  ~\scoop\apps\git-filter-repo\2.34.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=git-filter-repo%402.34.0%3a+Decompress+error&body=Failed+to+extract+files+from+C%3a%5cUsers%5crdibattista%5cscoop%5capps%5cgit-filter-repo%5c2.34.0%5cv2.34.0.zip.%0aLog+file%3a%0a++%7e%5cscoop%5capps%5cgit-filter-repo%5c2.34.0%5c7zip.log
ERROR This application failed to update: git-filter-repo
 
```

And the log: 

```
7-Zip 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26

Scanning the drive for archives:
1 file, 190207 bytes (186 KiB)

Extracting archive: C:\Users\rdibattista\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip
--
Path = C:\Users\rdibattista\scoop\apps\git-filter-repo\2.34.0\v2.34.0.zip
Type = zip
Physical Size = 190207
Comment = 235fed326910a90b3322bc535d643a9003f8d7e1


Sub items Errors: 2

Archives with Errors: 1

Sub items Errors: 2
```

**Comment by rashil2000** [comment] 2022-01-11 19:11
You are using a fork of Scoop. Please report the bug there.

**Comment by peterleif** [comment] 2022-01-12 01:16
Same here. https://github.com/ScoopInstaller/Main/commit/8b8da663ffc7d7c893ad728d9ff5bd751e36aa44 does not solve the issue.
The error message is the same as what I uploaded previously.

Since the error occurs in zip extraction, I think the changes in https://github.com/ScoopInstaller/Main/commit/8b8da663ffc7d7c893ad728d9ff5bd751e36aa44 is not relevant to this specific issue.

**Comment by rdbisme** [comment] 2022-01-12 02:22
@rashil2000 is the second time I get "you are using a fork, ask there" for an issue that is actually meant to be here. I don't understand why.

Anyway this issue must be reopened.

**Comment by rashil2000** [comment] 2022-01-12 03:52
@issaclin32 @HUMORCE @niheaven are you able to reproduce this bug? I can't.

**Comment by issaclin32** [comment] 2022-01-12 04:37
Cannot reproduce either.
My 7-zip log shows the same content, except that there are no errors.
I don't think old 7-zip will cause problems on **.zip**, and the hash is correct, so maybe it is due to "no empty space" or some HDD / RAM errors?

@rdbisme You probably need to run `7z t (SCOOP_DIR)\cache\git-filter-repo#2.34.0#https_github.com_newren_git-filter-repo_archive_v2.34.0.zip`, and see what is going on.

**Comment by peterleif** [comment] 2022-01-12 05:04
I am not https://github.com/rdbisme but I tried it.
`7z t -bb3 (path_to_zip)` shows no error and `7z e -bb3 (path_to_zip)` shows the error "The client does not have the requested permission."

I also tried extracting in a shell with the administrative permission, and the extraction succeeded.

On default, Windows does not allow creation of symbolic link by a normal user.
@rashil2000 @issaclin32 did you changed the setting or did you run 7z in a shell with the administrative permission?

**Comment by HUMORCE** [comment] 2022-01-12 05:10
@rashil2000 same as https://github.com/ScoopInstaller/Extras/issues/7425

**Comment by rashil2000** [comment] 2022-01-12 05:24
I have transferred it to Scoop core. Let's combine and track them there.

See https://github.com/ScoopInstaller/Scoop/issues/4647

**Closed by rashil2000** 2022-01-12 05:24 UTC
Labels: help-wanted

**Comment by niheaven** [comment] 2022-01-12 05:46
I tried in PS5 and PS7 with latest 'delelop' branch, and cannot reproduce.
