### ISSUE TITLE
scoop search error message

### ISSUE THREAD

**Issue by lepicsaintloup** [ScoopInstaller/Main#3107] opened 2021-12-20 04:05 UTC
## Bug Report

**Package Name:** scoop search

### Current Behaviour

When I search for a package it puts up an error message, although it appears to complete the search OK.

### Additional context/output
```
PS C:\Users\xxxx> scoop search context
Invoke-WebRequest: C:\Users\xxxx\scoop\apps\scoop\current\libexec\scoop-search.ps1:52
Line |
  52 |      $result = invoke-webrequest $url -UseBasicParsing | Select-Object …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/git#get-a-tree"}
```

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** windows-terminal 1.11.3471.0

#### Scoop Configuration

```json
//# {
  "SCOOP_BRANCH": "master",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "lastupdate": "2021-12-20T13:43:08.5643967+11:00"
}

```

**Comment by rashil2000** [comment] 2021-12-20 04:11
Duplicate of https://github.com/ScoopInstaller/Scoop/issues/4574

**Closed** 2021-12-20 04:11 UTC
Labels: bug
