### ISSUE TITLE
Ollama@0.3.0: decompress error

### ISSUE THREAD

**Issue by liangrongjie** [ScoopInstaller/Main#6061] opened 2024-07-30 08:56 UTC
WARN  Purging previous failed installation of Ollama.
ERROR 'Ollama' isn't installed correctly.
Removing older version (0.3.0).
'Ollama' was uninstalled.
Installing 'Ollama' (0.3.0) [64bit] from 'main' bucket
OllamaSetup.exe (298.5 MB) [==============================================================================================================================================] 100%
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from D:\scoop\apps\Ollama\0.3.0\OllamaSetup.exe.
Log file:
  D:\scoop\apps\Ollama\0.3.0\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=Ollama%400.3.0%3a+decompress+error

>   D:\scoop\apps\Ollama\0.3.0\innounp.log
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Critical error: The setup files are corrupted. Please obtain a new copy of the program.

**Comment by HUMORCE** [comment] 2024-08-01 20:22
Duplicate of #6065

**Closed by HUMORCE** 2024-08-01 20:22 UTC
