### ISSUE TITLE
7zip@23.00: decompress error

### ISSUE THREAD

**Issue by jwaller-ecc** [ScoopInstaller/Main#4801] opened 2023-05-15 12:23 UTC
Ran into this this morning:

```
Extracting 7z2300-x64.msi ... ERROR Exit code was 1618!
Failed to extract files from C:\Users\jwaller\scoop\apps\7zip\23.00\7z2300-x64.msi.
Log file:
  ~\scoop\apps\7zip\23.00\msi.log
```

Cheers!

**Comment by HUMORCE** [comment] 2023-05-15 21:10
Duplicate of #4799

**Closed by HUMORCE** 2023-05-15 21:10 UTC
