### ISSUE TITLE
[PROBLEM] with Python-language-server via Python 3.10.2

### ISSUE THREAD

**Issue by Xelbayria** [ScoopInstaller/Main#3331] opened 2022-02-25 07:08 UTC
## Bug Report

**Package Name:** Python 3.10.2

### Current Behaviour

I install python-language-server by running "pip install python-language-server[all]". All is good until I tried to run any command of pyls. 
do "python -m pyls --help" and try any command via the help info. Nothing works because they have been going on forever. I let it run for 10 minutes and no result. 

### Expected Behaviour

I expected the output to be short and not take much time.

### Additional context/output
> pyls -v 

> 2022-02-24 XX:XX:XX,XXX UTC - INFO - pyls.python_ls - Starting PythonLanguageServer IO language server

### Possible Cause

I believed the reason is non-default installation is the root of this. I cannot find a solution to this. The other is "The PATH" may be a factor in this. 

### System details

**Windows version:** 10 PRO

**OS architecture:** 64bit

**PowerShell version:** 5      1      19041  1320

**Comment by rashil2000** [comment] 2022-02-26 04:47
Have you installed all the prerequisites of python-language-server (inlcuding Jedi)?

**Comment by Xelbayria** [comment] 2022-02-26 08:25
> Have you installed all the prerequisites of python-language-server (including Jedi)?

yes. I have. Take a close look at [all] via "pip install python-language-server[all]". it installed all of the packages including Jedi.

**Comment by rashil2000** [comment] 2022-02-26 10:21
I don't think the command `pyls` is supposed to be used as-is. You need a language server to connect to it and talk to it. 

Can you show the output from a non-Scoop python installation so that we can compare?

**Comment by Xelbayria** [comment] 2022-02-26 20:03
> I don't think the command `pyls` is supposed to be used as-is. You need a language server to connect to it and talk to it.
> 
> Can you show the output from a non-Scoop python installation so that we can compare?

Alright. You meant to say that I should use the installer from the Python website and install it on my computer to see the difference? On Note: 
I used 
> python -m pyls --help
It works and shows me the command of what PYLS has but any of these commands don't work because it doesn't connect to the server.

**Comment by Xelbayria** [comment] 2022-02-27 03:50
Ok, what's the correct PATH for Ide-python where it can connect with the installation of Python and PYLS.

**Comment by rashil2000** [comment] 2022-02-27 04:44
Where are you installing IDE-Python from?

(Note that I'm closing this issue as it's not a bug in Scoop)

**Closed by rashil2000** 2022-02-27 04:44 UTC
Labels: bug

**Comment by rashil2000** [comment] 2022-02-27 04:57
It is possible that IDE-Python hard codes the location for Python installation (and provides no way to change that). In that case, using official installer would be best.

**Comment by Xelbayria** [comment] 2022-02-27 05:00
> It is possible that IDE-Python hard codes the location for Python installation (and provides no way to change that). In that case, using official installer would be best.

actually, it was half working fine. but it's also half not working. I mentioned that in my original post. I compared the official installer of Python and scoop

the big difference is "launcher" and IDE-Python use the PATH of windows 10 to know where is the python. I've confirmed this on my laptop.

**Comment by Xelbayria** [comment] 2022-02-27 06:40
It wasn't Python or Scoop's python. The atom editor has some problems. My laptop's atom editor is working fine but not on my computer.
great... one question gets answered, more questions have been unlocked. 

have a good day!. It will take me a while to solve this.

**Comment by rashil2000** [comment] 2022-02-27 06:42
Sure, no worries!
