### ISSUE TITLE
mysql-workbench@8.0.32: decompress error

### ISSUE THREAD

**Issue by laymonk** [ScoopInstaller/Main#4370] opened 2023-01-21 22:27 UTC
```
Failed to extract files from Y:\scoop\apps\mysql-workbench\8.0.32\mysql-workbench-community-8.0.32-winx64.msi.
Log file:
  Y:\scoop\apps\mysql-workbench\8.0.32\msi.log
```

Note that the log file mentioned above is empty

**Comment by HUMORCE** [comment] 2023-01-24 05:44
Duplicate of #4376

**Closed by HUMORCE** 2023-01-24 05:44 UTC
