### ISSUE TITLE
[Bug]: can't shim zstd 1.5.5

### ISSUE THREAD

**Issue by JP-Ellis** [ScoopInstaller/Main#4631] opened 2023-04-05 01:18 UTC
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

zstd

### Expected/Current Behaviour

The package should install correctly, and the shim to created.

Instead it errors and complains that `zstd.exe` doesn't exist:

```
zstd: 1.5.4 -> 1.5.5
Updating one outdated app:
Updating 'zstd' (1.5.4 -> 1.5.5)
Downloading new version
Loading zstd-v1.5.5-win64.zip from cache
Checking hash of zstd-v1.5.5-win64.zip ... ok.
Uninstalling 'zstd' (1.5.4)
Unlinking ~\scoop\apps\zstd\current
Installing 'zstd' (1.5.5) [64bit] from main bucket
Loading zstd-v1.5.5-win64.zip from cache
Extracting zstd-v1.5.5-win64.zip ... done.
Linking ~\scoop\apps\zstd\current => ~\scoop\apps\zstd\1.5.5
Creating shim for 'zstd'.
Can't shim 'zstd.exe': File doesn't exist.
```

### Steps to Reproduce

```console
❯ scoop update zstd
zstd: 1.5.4 -> 1.5.5
Updating one outdated app:
Updating 'zstd' (1.5.4 -> 1.5.5)
Downloading new version
Loading zstd-v1.5.5-win64.zip from cache
Checking hash of zstd-v1.5.5-win64.zip ... ok.
Uninstalling 'zstd' (1.5.4)
Unlinking ~\scoop\apps\zstd\current
Installing 'zstd' (1.5.5) [64bit] from main bucket
Loading zstd-v1.5.5-win64.zip from cache
Extracting zstd-v1.5.5-win64.zip ... done.
Linking ~\scoop\apps\zstd\current => ~\scoop\apps\zstd\1.5.5
Creating shim for 'zstd'.
Can't shim 'zstd.exe': File doesn't exist.
```

### Possible Solution

It would appear that the way the Zip file is organised has changed. Inspecting what scoop has extract, I see:

```
scoop\apps\zstd
├───1.5.4
│   ├───dll
│   ├───example
│   ├───include
│   └───static
├───1.5.5
│   └───zstd-v1.5.5-win64
│       ├───dll
│       ├───example
│       ├───include
│       └───static
└───current
    └───zstd-v1.5.5-win64
        ├───dll
        ├───example
        ├───include
        └───static
```

### Scoop and Buckets Version

```console
❯ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
a5dd22e2c (HEAD -> master, origin/master, origin/HEAD) vifm: Update to version 0.13

'main' bucket:
7624f87a7 (HEAD -> master, origin/master, origin/HEAD) zstd: Update to version 1.5.5

'nerd-fonts' bucket:
58f791f (HEAD -> master, origin/master, origin/HEAD) Font-Awesome: Update to version 6.4.0

'nonportable' bucket:
f49edef (HEAD -> master, origin/master, origin/HEAD) vokoscreenng-np: Update to version 3.5.0

'versions' bucket:
37b2f57d0 (HEAD -> master, origin/master, origin/HEAD) whatsapp-beta: Update to version 2.2316.1
```

### Scoop Config

```console
❯ scoop config

last_update         scoop_branch scoop_repo
-----------         ------------ ----------
2023-04-05 10:44:50 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by sitiom** [comment] 2023-04-05 06:52
Duplicate of #4630

**Closed** 2023-04-05 07:40 UTC
Labels: bug
