### ISSUE TITLE
tesseract-languages@4.1.0: decompress error

### ISSUE THREAD

**Issue by G4nda1f** [ScoopInstaller/Main#5792] opened 2024-05-05 19:30 UTC
Attempting to install results in this:

C:\Users\mark>scoop install main/tesseract-languages
Installing 'tesseract-languages' (4.1.0) [64bit] from 'main' bucket
Loading 4.1.0.zip from cache
Checking hash of 4.1.0.zip ... ok.
Loading equ.traineddata from cache
Checking hash of equ.traineddata ... ok.
Loading snum.traineddata from cache
Checking hash of snum.traineddata ... ok.
Extracting 4.1.0.zip ... ERROR Exit code was 2!
Failed to extract files from D:\users\mark\scoop\apps\tesseract-languages\4.1.0\4.1.0.zip.
Log file:
  D:\users\mark\scoop\apps\tesseract-languages\4.1.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=tesseract-languages%404.1.0%3a+decompress+error

C:\Users\mark>

**Comment by Uranite** [comment] 2024-07-02 09:00
https://github.com/ScoopInstaller/Main/issues/4874

**Comment by HUMORCE** [comment] 2024-11-08 09:04
Duplicate of #4874

**Closed by HUMORCE** 2024-11-08 09:04 UTC
