### ISSUE TITLE
mariadb@11.5.2: download via aria2 failed

### ISSUE THREAD

**Issue by lingkerio** [ScoopInstaller/Main#6270] opened 2024-10-21 16:10 UTC
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
WARN  To disable this warning, run 'scoop config aria2-warning-enabled false'.
Installing 'mariadb' (11.5.2) [64bit] from 'main' bucket
Starting download with aria2 ...
Download: 10/22 00:09:29 [ERROR] CUID#8 - Download aborted. URI=https://downloads.mariadb.com/MariaDB/mariadb-11.5.2/winDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://downloads.mariadb.com/MariaDB/mariadb-11.5.2/winx6Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 3294a4|ERR |       0B/s|D:/Scoop/cache/mariadb#11.5.2#5c6f178.zip
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 3) Resource was not found
ERROR https://downloads.mariadb.com/MariaDB/mariadb-11.5.2/winx64-packages/mariadb-11.5.2-winx64.zip
    referer=https://downloads.mariadb.com/MariaDB/mariadb-11.5.2/winx64-packages/
    dir=D:\Scoop\cache
    out=mariadb#11.5.2#5c6f178.zip

ERROR & 'D:\Scoop\apps\aria2\current\aria2c.exe' --input-file='D:\Scoop\cache\mariadb.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.4 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=4 --split=32 --max-connection-per-server=16 --min-split-size=4M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8892 --continue --summary-interval=0 --auto-save-interval=1 --all-proxy='127.0.0.1:7897'

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=mariadb%4011.5.2%3a+download+via+aria2+failed

**Comment by b1scu1t** [comment] 2024-10-22 03:39
This is a duplicate of https://github.com/ScoopInstaller/Main/issues/6263 . There is https://github.com/ScoopInstaller/Main/pull/6269 by @aliesbelik that is currently awaiting review.

**Closed** 2024-10-22 03:42 UTC
Labels: verified, manifest-fix-needed, help wanted

**Comment by lingkerio** [comment] 2024-10-22 03:44
> This is a duplicate of https://github.com/ScoopInstaller/Main/issues/6263 . There is https://github.com/ScoopInstaller/Main/pull/6269 by @aliesbelik that is currently awaiting review.

I will close this duplicate issue that I created and look forward to the prompt merging of the solution.
