### ISSUE TITLE
gcc@9.3.0-2:The remote server returned an error: (404) Not Found. URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid

### ISSUE THREAD

**Issue by HUAHUAI23** [ScoopInstaller/Main#2010] opened 2021-03-30 06:56 UTC
PS C:\Users\abc> scoop install gcc
Installing 'gcc' (9.3.0-2) [64bit]
mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz (13.9 MB) [===================================================] 100%
Checking hash of mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz ... ok.
mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz (3.1 MB) [======================================] 100%
Checking hash of mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz ... ok.
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid

**Comment by Phyllostachys** [comment] 2021-03-30 14:37
Same for gdb and bzip2. Looks like they switched from .tar.xz to .tar.zst too.

**Comment by chawyehsu** [comment] 2021-03-31 15:47
Duplicate of #1752

**Closed by chawyehsu** 2021-03-31 15:47 UTC
