### ISSUE TITLE
gcc@9.3.0-2: download via aria2 failed

### ISSUE THREAD

**Issue by TwoPizza9621536** [ScoopInstaller/Main#1892] opened 2021-03-07 02:59 UTC
Aria2
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'gcc' (9.3.0-2) [64bit]
Loading mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz from cache.
Loading mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache.
Starting download with aria2 ...
Download: 03/06 21:57:30 [ERROR] CUID#8 - Download aborted. URI=http://repo.msysDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.Download: 03/06 21:57:30 [ERROR] CUID#13 - Download aborted. URI=http://repo.msyDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.Download: [DL:3.6MiB][#e6a164 608KiB/32MiB(1%)][#24ea9c 528KiB/9.6MiB(5%)][#b331Download: 03/06 21:57:31 [ERROR] CUID#32 - Download aborted. URI=http://repo.msyDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.Download: [DL:14MiB][#e6a164 9.2MiB/32MiB(28%)][#24ea9c 6.0MiB/9.6MiB(62%)][#974Download: 03/06 21:57:32 [ERROR] CUID#37 - Download aborted. URI=http://repo.msyDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.Download: 03/06 21:57:32 [ERROR] CUID#40 - Download aborted. URI=http://repo.msyDownload: Exception: [AbstractCommand.cc:351] errorCode=3 URI=http://repo.msys2.Download: Download Results:                                           7%)]ound
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 434c6b|ERR |       0B/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz
Download: 1a956a|ERR |       0B/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz
Download: 656bfc|OK  |   1.0MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gcc-libs-9.3.0-2-any.pkg.tar.xz
Download: b331b5|OK  |   0.9MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gcc-libgfortran-9.3.0-2-any.pkg.tar.xz
Download: 50841d|OK  |   704KiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gmp-6.2.0-1-any.pkg.tar.xz
Download: 032f1b|ERR |       0B/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz
Download: 0a4c88|OK  |   3.9MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-isl-0.22.1-1-any.pkg.tar.xz
Download: 62f3f1|OK  |   6.9MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-libwinpthread-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz
Download: b7da16|OK  |    10MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-make-4.3-1-any.pkg.tar.xz
Download: 247f4e|OK  |    25MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-mpc-1.1.0-1-any.pkg.tar.xz
Download: 974e7c|OK  |   5.9MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-headers-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz
Download: 40eaf4|OK  |    24MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-mpfr-4.0.2-2-any.pkg.tar.xz
Download: 7e9a24|OK  |   4.1MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz
Download: dee5be|OK  |   4.6MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-winpthreads-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz
Download: 97cf85|ERR |       0B/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz
Download: a7c2f4|ERR |       0B/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz
Download: 24ea9c|OK  |   2.8MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gcc-fortran-9.3.0-2-any.pkg.tar.xz
Download: e6a164|OK  |   6.4MiB/s|C:/Users/Samgo/scoop/cache/gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gcc-9.3.0-2-any.pkg.tar.xz
Download: Status Legend:
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 3) Resource was not found
ERROR http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-9.3.0-2-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gcc-9.3.0-2-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-fortran-9.3.0-2-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gcc-fortran-9.3.0-2-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libgfortran-9.3.0-2-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gcc-libgfortran-9.3.0-2-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gcc-libs-9.3.0-2-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gcc-libs-9.3.0-2-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gettext-0.19.8.1-8-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gmp-6.2.0-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-gmp-6.2.0-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-headers-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-headers-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-isl-0.22.1-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-isl-0.22.1-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-libwinpthread-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-libwinpthread-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-make-4.3-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-make-4.3-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-mpc-1.1.0-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-mpc-1.1.0-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-mpfr-4.0.2-2-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-mpfr-4.0.2-2-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-pkg-config-0.29.2-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-winpthreads-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-winpthreads-git-8.0.0.5814.9dbf4cc1-1-any.pkg.tar.xz
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz
    referer=http://repo.msys2.org/mingw/x86_64/
    dir=C:\Users\Samgo\scoop\cache
    out=gcc#9.3.0-2#http_repo.msys2.org_mingw_x86_64_mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz

ERROR & 'C:\Users\Samgo\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Samgo\scoop\cache\gcc.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=6360 --continue --summary-interval 0

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=gcc%409.3.0-2%3a+download+via+aria2+failed
=========================================================
normal / without aria
Installing 'gcc' (9.3.0-2) [64bit]
Loading mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-binutils-2.34-1-any.pkg.tar.xz ... ok.
Loading mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz from cache
Checking hash of mingw-w64-x86_64-crt-git-8.0.0.5815.9517d302-1-any.pkg.tar.xz ... ok.
The remote server returned an error: (404) Not Found.
URL http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz is not valid

**Comment by chawyehsu** [comment] 2021-03-10 01:49
Duplicate of #1752

**Closed by chawyehsu** 2021-03-10 01:49 UTC
Labels: help-wanted, package-fix-needed, verified
