### ISSUE TITLE
gcc@9.3.0-2: download via aria2 failed

### ISSUE THREAD

**Issue by kleeon** [ScoopInstaller/Main#1859] opened 2021-02-23 15:35 UTC
`scoop install gcc` fails.
Following URL returns 404:

http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-expat-2.2.9-1-any.pkg.tar.xz

**Comment by chawyehsu** [comment] 2021-03-10 01:49
Duplicate of #1752

**Closed by chawyehsu** 2021-03-10 01:49 UTC
Labels: help-wanted, package-fix-needed, verified
