### ISSUE TITLE
python@3.9.5: decompress error

### ISSUE THREAD

**Issue by L1onKo** [ScoopInstaller/Main#2210] opened 2021-05-22 11:36 UTC
```
scoop install python
Installing 'python' (3.9.5) [64bit]
Loading python-3.9.5-amd64.exe from cache
Checking hash of python-3.9.5-amd64.exe ... ok.
Loading install-pep-514.reg from cache
Checking hash of install-pep-514.reg ... ok.
Loading uninstall-pep-514.reg from cache
Checking hash of uninstall-pep-514.reg ... ok.
Running pre-install script...
Running installer script...
ERROR Exit code was 1603!
Failed to extract files from C:\Users\xxx\scoop\apps\python\3.9.5\_tmp\AttachedContainer\core.msi.
Log file:
  ~\scoop\apps\python\3.9.5\_tmp\AttachedContainer\msi.log
```

**Comment by L1onKo** [comment] 2021-05-22 11:37
msi.log:
```
=== Logging started: 5/22/2021  14:34:05 ===
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2503. The arguments are: , , 
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2502. The arguments are: , , 
=== Logging stopped: 5/22/2021  14:34:05 ===

```

**Comment by Valinor** [comment] 2021-10-05 06:05
I close this issue (new manifest in 3.9.7). If this issue remain in 3.9.7 (can't reproduce here with 3.9.7), open a new issue with 3.9.7.
Check NTFS permissions for C:\\Windows\\Temp and attach it to the new issue

MSI installer errors 2502 and 2503 in Windows 10, Windows 8.1 and Windows 7 usually indicate that the folder C:\\Windows\\Temp has incorrect NTFS permissions. To let Windows Installer operate normally, this folder need to have full write access permissions and ownership for your user account.

**Closed by Valinor** 2021-10-05 06:05 UTC
